version: '3.3'

services:
  klustair:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KUBECTL_VERSION: "${KUBECTL_VERSION:-v1.17.0}"
    image: klustair:latest
    command: ["tail", "-f", "/dev/null"]
    restart: on-failure
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ANCHORE_CLI_USER=${ANCHORE_CLI_USER}
      - ANCHORE_CLI_PASS=${ANCHORE_CLI_PASS}
    volumes:
      - ${PATH_LOCAL_KUBECONFIG}:/kube.config