version: '3.3'

services:
  klustair-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KUBECTL_VERSION: "${KUBECTL_VERSION:-v1.17.0}"
    image: klustair:latest
    container_name: klustair-runner
    command: ["tail", "-f", "/dev/null"]
    restart: on-failure
    working_dir: /app
    environment:
      - KLUSTAIR_APITOKEN=${KLUSTAIR_APITOKEN}
      - KLUSTAIR_CONFIGKEY=${KLUSTAIR_CONFIGKEY}
      - KLUSTAIR_APIHOST=${KLUSTAIR_APIHOST}
      - KLUSTAIR_LIMITDATE=${KLUSTAIR_LIMITDATE}
      - KLUSTAIR_LIMITNR=${KLUSTAIR_LIMITNR}
      - KUBECONFIG=/etc/klustair/kube.config
    volumes:
      - ${PATH_LOCAL_KUBECONFIG}:/etc/klustair/kube.config
      - ./app:/app