version: '3.3'

services:
  klustair:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KUBECTL_VERSION: "${KUBECTL_VERSION:-v1.17.0}"
    image: klustair:latest
    command: ["tail", "-f", "/dev/null"]
    restart: on-failure
    environment:
      - MONGODB_CONNECTION=${MONGODB_CONNECTION}
    volumes:
      - ${PATH_LOCAL_KUBECONFIG}:/kube.config
  database:
    container_name: klustair-mongo-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db