version: '3.3'

services:
  klustair:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KUBECTL_VERSION: "${KUBECTL_VERSION:-v1.17.0}"
    image: klustair:latest
    command: ["tail", "-f", "/dev/null"]
    restart: on-failure
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ANCHORE_CLI_USER=${ANCHORE_CLI_USER}
      - ANCHORE_CLI_PASS=${ANCHORE_CLI_PASS}
    volumes:
      - ${PATH_LOCAL_KUBECONFIG}:/kube.config
  klustair-frontend:
    container_name: klustair-frontend
    image: gicara/klustair-frontend:latest
    restart: on-failure
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:80
  database:
    container_name: klustair-mongo-db
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: klustair
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db