apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kubeconfig
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
#  annotations:
#    "helm.sh/hook": "pre-install"
#    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  "kube.config": {{ .Files.Get "secrets/kube.config" | b64enc | quote }}